### PR TITLE
Set up a basic demo site

### PR DESCRIPTION
**Pull request by bebraw**
To start developing against it (hot loading) hit `npm start`. You can generate `gh-pages` using `npm run gh-pages`. It can be deployed to the `gh-pages` branch by hitting `npm run deploy-gh-pages`.

The demo site has been split in two parts. The upper half is meant for a basic demo. I just copied the one that exists already. In addition you could render each field here in a separate section. The lower half just renders README.md (highlighting applied).

Related to #23.

### CODE REVIEW

**Comment by odf** [comment]
Looking pretty sweet. One tiny thing I've noticed is that my browser (Firefox 36 on Ubuntu) does not place the header at the top of the page by default, so it obscures the top of the first section. An explicit `top: 0;` in the CSS seems to fix that. The same thing happens with the Reactabular page, by the way.
Is it possible to implement deployment via a shell script so that it's more obvious which git commands are actually issued? A JavaScript program executing shell commands from somewhere within its bowels is not my preferred way of doing things.

**Comment by bebraw** [comment]
@odf, I fixed the header issue. Thanks for pointing it out. Would something [like this](https://gist.github.com/domenic/ec8b0fc8ab45f39403dd) work for `gh-pages`? As you can see it's possible to hook up the script with Travis making the process automated. Alternatively we can just pick the script, modify as needed and go with that.

**Comment by odf** [comment]
Yeah, that's more like it. Call me old-fashioned, but I like to know what I'm actually doing. :-)

Hooking the project up with Travis just to automate this seems a bit overkill at this point, but I'm not fundamentally opposed to it.

**Comment by bebraw** [comment]
@odf Ok. I'll start by doing a simple deploy script. Seems straightforward enough.

The cool thing about Travis is that it would allow you to run tests over components. I've been using [Jest](http://facebook.github.io/jest/) myself. But that's something for you to think about.

**Comment by bebraw** [comment]
@odf I set up a little script. It creates a repo to `/gh-pages` directory and then force pushes it to the `gh-pages` branch. Here's [a sample build](http://bebraw.github.io/plexus-form/).

**Comment by odf** [comment]
Looking great! Thanks for the effort!

**Comment by bebraw** [comment]
@odf What are your next plans? If you have particular tasks in mind, could you open up issues to help with discussion? I would love to see an improved release sometime in the near future.

**Comment by odf** [comment]
Honestly, I'm not really maintaining this little library in a very planned fashion, and between all my big bad long-term projects, on and off the clock, I don't see myself being able to do that any time soon, either. As far as I am concerned, we might just as well push out a new release right about now with all the changes since v0.1.0.

In the longer term, let's just say I would not hold it against you if you decided to go ahead with your own fork. If this were my own private project, I'd have given you commit rights by now and maybe even considered offering a handover, but as things are, I can't really do either of these things.

**Comment by bebraw** [comment]
> Honestly, I'm not really maintaining this little library in a very planned fashion, and between all my big bad long-term projects, on and off the clock, I don't see myself being able to do that any time soon, either. As far as I am concerned, we might just as well push out a new release right about now with all the changes since v0.1.0.

Ok. That would be fine. Please give the demo a quick go and let me know if you find any regressions. I'll take care of those.

> In the longer term, let's just say I would not hold it against you if you decided to go ahead with your own fork. If this were my own private project, I'd have given you commit rights by now and maybe even considered offering a handover, but as things are, I can't really do either of these things.

Yeah, licensing allows that. Just need to retain attribution. This is a good option. :)

**Pull request merged**
